// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 送货员送货详情
    /// </summary>
    [Table("dlv_deliver_detail")]
    public partial class DlvDeliverDetail
    {
        /// <summary>
        /// 日期
        /// </summary>
        [Key]
        [Column("crdate", TypeName = "date")]
        public DateTime Crdate { get; set; }
        /// <summary>
        /// 送货人id
        /// </summary>
        [Key]
        [Column("deliverid")]
        public int Deliverid { get; set; }
        /// <summary>
        /// 供货商id
        /// </summary>
        [Key]
        [Column("supplierid")]
        public int Supplierid { get; set; }
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 商品数量
        /// </summary>
        [Column("product_count")]
        public int? ProductCount { get; set; }
    }
}