// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 送货行为追踪
    /// </summary>
    [Table("dlv_deliver_track_detail")]
    public partial class DlvDeliverTrackDetail
    {
        /// <summary>
        /// 送货追踪id
        /// </summary>
        [Key]
        [Column("trackid")]
        public int Trackid { get; set; }
        /// <summary>
        /// 状态 1到达取货地点 2离开取货地点 3到达送货地点
        /// </summary>
        [Column("state")]
        public int State { get; set; }
        /// <summary>
        /// 供货商id
        /// </summary>
        [Column("supplierid")]
        public int Supplierid { get; set; }
        /// <summary>
        /// 送达公司id
        /// </summary>
        [Column("companyid")]
        public int Companyid { get; set; }
        /// <summary>
        /// 时间
        /// </summary>
        [Column("crtime", TypeName = "date")]
        public DateTime Crtime { get; set; }
    }
}