// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 公司的主供货商历史记录
    /// </summary>
    [Table("his_company_supplier")]
    public partial class HisCompanySupplier
    {
        /// <summary>
        /// 日期
        /// </summary>
        [Key]
        [Column("crdate", TypeName = "date")]
        public DateTime Crdate { get; set; }
        /// <summary>
        /// 公司id
        /// </summary>
        [Key]
        [Column("companyid")]
        public int Companyid { get; set; }
        /// <summary>
        /// 供货商id
        /// </summary>
        [Column("suplierid")]
        public int Suplierid { get; set; }
    }
}