// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 公司与供货商关系
    /// </summary>
    [Table("r_company_supplier")]
    [Index(nameof(Suplierid), Name = "fk_suplierid_2")]
    public partial class RCompanySupplier
    {
        /// <summary>
        /// 公司id
        /// </summary>
        [Key]
        [Column("companyid")]
        public int Companyid { get; set; }
        /// <summary>
        /// 供货商id
        /// </summary>
        [Column("suplierid")]
        public int Suplierid { get; set; }
        /// <summary>
        /// 起始日期
        /// </summary>
        [Key]
        [Column("start_date", TypeName = "date")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        [Column("end_date", TypeName = "date")]
        public DateTime EndDate { get; set; }

        [ForeignKey(nameof(Companyid))]
        [InverseProperty(nameof(TCompany.RCompanySupplier))]
        public virtual TCompany Company { get; set; }
        [ForeignKey(nameof(Suplierid))]
        [InverseProperty(nameof(SpUser.RCompanySupplier))]
        public virtual SpUser Suplier { get; set; }
    }
}