// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 部分商品的指定供货商
    /// </summary>
    [Table("r_product_suplier")]
    [Index(nameof(Suplierid), Name = "fk_suplierid")]
    public partial class RProductSuplier
    {
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 供货商id
        /// </summary>
        [Key]
        [Column("suplierid")]
        public int Suplierid { get; set; }
        /// <summary>
        /// 类型 0由其供货 1不由其供货
        /// </summary>
        [Key]
        [Column("type")]
        public int Type { get; set; }
        /// <summary>
        /// 开始日期
        /// </summary>
        [Key]
        [Column("start_date", TypeName = "date")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        [Column("end_date", TypeName = "date")]
        public DateTime EndDate { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Productid))]
        [InverseProperty(nameof(TProduct.RProductSuplier))]
        public virtual TProduct Product { get; set; }
        [ForeignKey(nameof(Suplierid))]
        [InverseProperty(nameof(SpUser.RProductSuplier))]
        public virtual SpUser Suplier { get; set; }
    }
}