// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 供货商供货异常情况
    /// </summary>
    [Table("sp_exception")]
    public partial class SpException
    {
        /// <summary>
        /// 供货商id
        /// </summary>
        [Key]
        [Column("supplierid")]
        public int Supplierid { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        [Key]
        [Column("crdate", TypeName = "date")]
        public DateTime Crdate { get; set; }
        /// <summary>
        /// 异常描述
        /// </summary>
        [Required]
        [Column("msg")]
        [StringLength(256)]
        public string Msg { get; set; }
        /// <summary>
        /// 状态 0未处理 1已处理
        /// </summary>
        [Column("state")]
        public int State { get; set; }
        /// <summary>
        /// 受影响的商品数量
        /// </summary>
        [Column("product_count")]
        public int ProductCount { get; set; }
        /// <summary>
        /// 损失评论（元）
        /// </summary>
        [Column("loss_value")]
        public int LossValue { get; set; }
    }
}