// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 订单中的商品的供货商
    /// </summary>
    [Table("sp_order_product_supplier")]
    public partial class SpOrderProductSupplier
    {
        /// <summary>
        /// 订单号
        /// </summary>
        [Key]
        [Column("orderid")]
        [StringLength(32)]
        public string Orderid { get; set; }
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 供货商
        /// </summary>
        [Column("supplierid")]
        public int Supplierid { get; set; }
        /// <summary>
        /// 状态 0正常 1未出货
        /// </summary>
        [Column("state")]
        public int State { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        [Column("msg")]
        [StringLength(256)]
        public string Msg { get; set; }
    }
}