// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 购物车
    /// </summary>
    [Table("t_cart")]
    [Index(nameof(Productid), Name = "fkproductid_idx")]
    [Index(nameof(Userid), Name = "fkuserid_idx")]
    public partial class TCart
    {
        /// <summary>
        /// 用户id
        /// </summary>
        [Key]
        [Column("userid")]
        public int Userid { get; set; }
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 商品数量
        /// </summary>
        [Column("count")]
        public int Count { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Productid))]
        [InverseProperty(nameof(TProduct.TCart))]
        public virtual TProduct Product { get; set; }
        [ForeignKey(nameof(Userid))]
        [InverseProperty(nameof(TUser.TCart))]
        public virtual TUser User { get; set; }
    }
}