// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 购物车
    /// </summary>
    public partial class TCart
    {
        public int Id { get; set; }
        /// <summary>
        /// 用户id
        /// </summary>
        public uint Userid { get; set; }
        /// <summary>
        /// 商品id
        /// </summary>
        public uint Productid { get; set; }
        /// <summary>
        /// 商品数量
        /// </summary>
        public uint Count { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime Crtime { get; set; }
    }
}