// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 商品分类
    /// </summary>
    public partial class TCategory
    {
        public TCategory()
        {
            TProduct = new HashSet<TProduct>();
        }

        /// <summary>
        /// 商品分类id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 商品分类名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 状态0正常 1禁用
        /// </summary>
        public int State { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime Crtime { get; set; }

        public virtual ICollection<TProduct> TProduct { get; set; }
    }
}