// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 公司
    /// </summary>
    [Table("t_company")]
    [Index(nameof(Code), Name = "IX_CODE", IsUnique = true)]
    [Index(nameof(Name), Name = "IX_NAME", IsUnique = true)]
    public partial class TCompany
    {
        public TCompany()
        {
            RCompanySupplier = new HashSet<RCompanySupplier>();
            TUser = new HashSet<TUser>();
        }

        /// <summary>
        /// 公司id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 公司名字
        /// </summary>
        [Column("name")]
        [StringLength(64)]
        public string Name { get; set; }
        /// <summary>
        /// 唯一编码
        /// </summary>
        [Column("code")]
        [StringLength(64)]
        public string Code { get; set; }
        /// <summary>
        /// 公司地址
        /// </summary>
        [Column("address")]
        [StringLength(128)]
        public string Address { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime? Crtime { get; set; }

        [InverseProperty("Company")]
        public virtual ICollection<RCompanySupplier> RCompanySupplier { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<TUser> TUser { get; set; }
    }
}