// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 评论
    /// </summary>
    [Table("t_comment")]
    [Index(nameof(Orderid), Name = "fkorderid_idx")]
    public partial class TComment
    {
        /// <summary>
        /// id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 订单编号
        /// </summary>
        [Required]
        [Column("orderid")]
        [StringLength(32)]
        public string Orderid { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        [Required]
        [Column("msg")]
        [StringLength(256)]
        public string Msg { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Orderid))]
        [InverseProperty(nameof(TOrder.TComment))]
        public virtual TOrder Order { get; set; }
    }
}