// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 公司
    /// </summary>
    public partial class TCompany
    {
        public TCompany()
        {
            TUser = new HashSet<TUser>();
        }

        /// <summary>
        /// 公司id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 公司名字
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 唯一编码
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// 公司地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? Crtime { get; set; }

        public virtual ICollection<TUser> TUser { get; set; }
    }
}