// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 优惠卷信息
    /// </summary>
    [Table("t_coupon")]
    [Index(nameof(Name), Name = "ix_name", IsUnique = true)]
    public partial class TCoupon
    {
        public TCoupon()
        {
            TUserCoupon = new HashSet<TUserCoupon>();
        }

        /// <summary>
        /// 优惠券id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 优惠卷名称
        /// </summary>
        [Required]
        [Column("name")]
        [StringLength(128)]
        public string Name { get; set; }
        /// <summary>
        /// 优惠金额
        /// </summary>
        [Column("money")]
        public decimal Money { get; set; }
        /// <summary>
        /// 使用开始日期
        /// </summary>
        [Column("start_time", TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        /// <summary>
        /// 使用截止日期
        /// </summary>
        [Column("end_time", TypeName = "datetime")]
        public DateTime EndTime { get; set; }
        /// <summary>
        /// 优惠卷创建时间
        /// </summary>
        [Column("crtime", TypeName = "timestamp")]
        public DateTime Crtime { get; set; }

        [InverseProperty("Coupon")]
        public virtual ICollection<TUserCoupon> TUserCoupon { get; set; }
    }
}