// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 优惠卷信息
    /// </summary>
    public partial class TCoupon
    {
        public TCoupon()
        {
            TUserCoupon = new HashSet<TUserCoupon>();
        }

        /// <summary>
        /// 主键
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 优惠卷名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 优惠金额
        /// </summary>
        public decimal Money { get; set; }
        /// <summary>
        /// 使用开始日期
        /// </summary>
        public DateTime StartTime { get; set; }
        /// <summary>
        /// 使用截止日期
        /// </summary>
        public DateTime EndTime { get; set; }
        /// <summary>
        /// 优惠卷创建时间
        /// </summary>
        public DateTime Crtime { get; set; }

        public virtual ICollection<TUserCoupon> TUserCoupon { get; set; }
    }
}