// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 用户反馈
    /// </summary>
    [Table("t_feedback")]
    [Index(nameof(Userid), Name = "fkuserid_idx")]
    public partial class TFeedback
    {
        /// <summary>
        /// id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 用户id
        /// </summary>
        [Column("userid")]
        public int Userid { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        [Required]
        [Column("msg")]
        [StringLength(512)]
        public string Msg { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }
        /// <summary>
        /// 回复内容
        /// </summary>
        [Column("replay")]
        [StringLength(512)]
        public string Replay { get; set; }
        /// <summary>
        /// 回复时间
        /// </summary>
        [Column("replay_time", TypeName = "datetime")]
        public DateTime? ReplayTime { get; set; }

        [ForeignKey(nameof(Userid))]
        [InverseProperty(nameof(TUser.TFeedback))]
        public virtual TUser User { get; set; }
    }
}