// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 消息中心
    /// </summary>
    [Table("t_message")]
    [Index(nameof(Userid), Name = "fkuserid_idx")]
    public partial class TMessage
    {
        /// <summary>
        /// id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 用户id
        /// </summary>
        [Column("userid")]
        public int Userid { get; set; }
        /// <summary>
        /// 消息内容
        /// </summary>
        [Required]
        [Column("message")]
        [StringLength(640)]
        public string Message { get; set; }
        /// <summary>
        /// 是否已读(0未读 1已读)
        /// </summary>
        [Column("isread")]
        public int Isread { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Userid))]
        [InverseProperty(nameof(TUser.TMessage))]
        public virtual TUser User { get; set; }
    }
}