// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 公告信息
    /// </summary>
    [Table("t_notice")]
    public partial class TNotice
    {
        /// <summary>
        /// 公告id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 公告内容
        /// </summary>
        [Required]
        [Column("content")]
        [StringLength(512)]
        public string Content { get; set; }
        /// <summary>
        /// 公告生效起始日期
        /// </summary>
        [Column("start_date", TypeName = "date")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 公告生效结束日期
        /// </summary>
        [Column("end_date", TypeName = "date")]
        public DateTime EndDate { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }
    }
}