// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 订单中使用的优惠卷
    /// </summary>
    public partial class TOrderCoupon
    {
        /// <summary>
        /// 订单编号
        /// </summary>
        public string Orderid { get; set; }
        /// <summary>
        /// 优惠卷id
        /// </summary>
        public int Couponid { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public int Count { get; set; }
        /// <summary>
        /// 总金额
        /// </summary>
        public decimal Money { get; set; }
    }
}