// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 微信支付回调
    /// </summary>
    [Table("t_order_callback")]
    public partial class TOrderCallback
    {
        /// <summary>
        /// 订单编号
        /// </summary>
        [Key]
        [Column("orderid")]
        [StringLength(32)]
        public string Orderid { get; set; }
        /// <summary>
        /// 用户id
        /// </summary>
        [Column("userid")]
        public int Userid { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        [Column("money")]
        public int Money { get; set; }
        /// <summary>
        /// 支付完成日期
        /// </summary>
        [Column("crdate", TypeName = "date")]
        public DateTime Crdate { get; set; }
        /// <summary>
        /// 支付完成时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Orderid))]
        [InverseProperty(nameof(TOrder.TOrderCallback))]
        public virtual TOrder Order { get; set; }
    }
}