// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 订单中的商品信息
    /// </summary>
    [Table("t_order_product")]
    [Index(nameof(Productid), Name = "fkproducts")]
    public partial class TOrderProduct
    {
        /// <summary>
        /// 订单编号
        /// </summary>
        [Key]
        [Column("orderid")]
        [StringLength(32)]
        public string Orderid { get; set; }
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        [Required]
        [Column("productName")]
        [StringLength(128)]
        public string ProductName { get; set; }
        /// <summary>
        /// 单价
        /// </summary>
        [Column("price")]
        public decimal Price { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        [Column("count")]
        public int Count { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        [Column("money")]
        public decimal Money { get; set; }
        /// <summary>
        /// 类别 0普通 1早餐 2午餐 3晚餐
        /// </summary>
        [Column("type")]
        public int Type { get; set; }
        /// <summary>
        /// 商品图片
        /// </summary>
        [Required]
        [Column("img")]
        [StringLength(256)]
        public string Img { get; set; }

        [ForeignKey(nameof(Orderid))]
        [InverseProperty(nameof(TOrder.TOrderProduct))]
        public virtual TOrder Order { get; set; }
    }
}