// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 订单中使用的优惠卷
    /// </summary>
    [Table("t_order_coupon")]
    [Index(nameof(Couponid), Name = "fkcouponss")]
    public partial class TOrderCoupon
    {
        /// <summary>
        /// 订单编号
        /// </summary>
        [Key]
        [Column("orderid")]
        [StringLength(32)]
        public string Orderid { get; set; }
        /// <summary>
        /// 优惠卷id
        /// </summary>
        [Key]
        [Column("couponid")]
        public int Couponid { get; set; }
        /// <summary>
        /// 优惠券名称
        /// </summary>
        [Required]
        [Column("couponName")]
        [StringLength(128)]
        public string CouponName { get; set; }
        /// <summary>
        /// 优惠券面额
        /// </summary>
        [Column("price")]
        public decimal Price { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        [Column("count")]
        public int Count { get; set; }
        /// <summary>
        /// 总金额
        /// </summary>
        [Column("money")]
        public decimal Money { get; set; }

        [ForeignKey(nameof(Orderid))]
        [InverseProperty(nameof(TOrder.TOrderCoupon))]
        public virtual TOrder Order { get; set; }
    }
}