// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 商品定向公司展示
    /// </summary>
    [Table("t_product_company")]
    public partial class TProductCompany
    {
        /// <summary>
        /// 商品id
        /// </summary>
        [Key]
        [Column("productid")]
        public int Productid { get; set; }
        /// <summary>
        /// 公司id
        /// </summary>
        [Key]
        [Column("companyid")]
        public int Companyid { get; set; }
        /// <summary>
        /// 起始日期
        /// </summary>
        [Key]
        [Column("start_date", TypeName = "date")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        [Column("end_date", TypeName = "date")]
        public DateTime EndDate { get; set; }
    }
}