// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 商品
    /// </summary>
    public partial class TProduct
    {
        /// <summary>
        /// 商品id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 商品分类
        /// </summary>
        public int Category { get; set; }
        /// <summary>
        /// 价格
        /// </summary>
        public decimal Price { get; set; }
        /// <summary>
        /// 销量
        /// </summary>
        public int Sales { get; set; }
        /// <summary>
        /// 商品图片
        /// </summary>
        public string Img { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime Crtime { get; set; }

        public virtual TCategory CategoryNavigation { get; set; }
    }
}