// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 用户的优惠卷
    /// </summary>
    [Table("t_user_coupon")]
    [Index(nameof(Couponid), Name = "fk_coupon_idx")]
    public partial class TUserCoupon
    {
        /// <summary>
        /// 用户id
        /// </summary>
        [Key]
        [Column("userid")]
        public int Userid { get; set; }
        /// <summary>
        /// 优惠卷id
        /// </summary>
        [Key]
        [Column("couponid")]
        public int Couponid { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        [Column("count")]
        public int Count { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }

        [ForeignKey(nameof(Couponid))]
        [InverseProperty(nameof(TCoupon.TUserCoupon))]
        public virtual TCoupon Coupon { get; set; }
        [ForeignKey(nameof(Userid))]
        [InverseProperty(nameof(TUser.TUserCoupon))]
        public virtual TUser User { get; set; }
    }
}