// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 用户
    /// </summary>
    [Table("t_user")]
    [Index(nameof(Companyid), Name = "fk_company_idx")]
    [Index(nameof(Code), Name = "ix_code", IsUnique = true)]
    public partial class TUser
    {
        public TUser()
        {
            TCart = new HashSet<TCart>();
            TFeedback = new HashSet<TFeedback>();
            TMessage = new HashSet<TMessage>();
            TUserCoupon = new HashSet<TUserCoupon>();
        }

        /// <summary>
        /// 用户id
        /// </summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 唯一编码
        /// </summary>
        [Required]
        [Column("code")]
        [StringLength(64)]
        public string Code { get; set; }
        /// <summary>
        /// 公司id
        /// </summary>
        [Column("companyid")]
        public int Companyid { get; set; }
        /// <summary>
        /// 昵称
        /// </summary>
        [Required]
        [Column("nick")]
        [StringLength(32)]
        public string Nick { get; set; }
        /// <summary>
        /// 头像图片
        /// </summary>
        [Required]
        [Column("headimg")]
        [StringLength(256)]
        public string Headimg { get; set; }
        /// <summary>
        /// 手机号
        /// </summary>
        [Required]
        [Column("phone")]
        [StringLength(32)]
        public string Phone { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("crtime", TypeName = "datetime")]
        public DateTime Crtime { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        [Column("gender")]
        public int Gender { get; set; }

        [ForeignKey(nameof(Companyid))]
        [InverseProperty(nameof(TCompany.TUser))]
        public virtual TCompany Company { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TCart> TCart { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TFeedback> TFeedback { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TMessage> TMessage { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TUserCoupon> TUserCoupon { get; set; }
    }
}