// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Model.Database
{
    /// <summary>
    /// 微信支付回调数据
    /// </summary>
    [Table("t_wx_order_callback")]
    [Index(nameof(OutTradeNo), Name = "PK_out_trade_no")]
    public partial class TWxOrderCallback
    {
        /// <summary>
        /// 微信支付订单号
        /// </summary>
        [Key]
        [Column("transaction_id")]
        [StringLength(64)]
        public string TransactionId { get; set; }
        /// <summary>
        /// 商户订单号
        /// </summary>
        [Column("out_trade_no")]
        [StringLength(128)]
        public string OutTradeNo { get; set; }
        /// <summary>
        /// 应用ID
        /// </summary>
        [Column("appid")]
        [StringLength(64)]
        public string Appid { get; set; }
        /// <summary>
        /// 商户号
        /// </summary>
        [Column("mchid")]
        [StringLength(64)]
        public string Mchid { get; set; }
        /// <summary>
        /// 交易类型
        /// </summary>
        [Column("trade_type")]
        [StringLength(64)]
        public string TradeType { get; set; }
        /// <summary>
        /// 交易状态
        /// </summary>
        [Column("trade_state")]
        [StringLength(64)]
        public string TradeState { get; set; }
        /// <summary>
        /// 交易状态描述
        /// </summary>
        [Column("trade_state_desc")]
        [StringLength(256)]
        public string TradeStateDesc { get; set; }
        /// <summary>
        /// 付款银行
        /// </summary>
        [Column("bank_type")]
        [StringLength(64)]
        public string BankType { get; set; }
        /// <summary>
        /// 附加数据，在查询API和支付通知中原样返可作为自定义参数使用
        /// </summary>
        [Column("attach")]
        [StringLength(256)]
        public string Attach { get; set; }
        /// <summary>
        /// 支付完成时间
        /// </summary>
        [Column("success_time", TypeName = "datetime")]
        public DateTime? SuccessTime { get; set; }
        /// <summary>
        /// 支付者标识
        /// </summary>
        [Column("openid")]
        [StringLength(64)]
        public string Openid { get; set; }
        /// <summary>
        /// 总金额
        /// </summary>
        [Column("total")]
        public int? Total { get; set; }
        /// <summary>
        /// 用户支付金额
        /// </summary>
        [Column("payer_total")]
        public int? PayerTotal { get; set; }
        /// <summary>
        /// 货币类型
        /// </summary>
        [Column("currency")]
        [StringLength(64)]
        public string Currency { get; set; }
        /// <summary>
        /// 用户支付币种
        /// </summary>
        [Column("payer_currency")]
        [StringLength(64)]
        public string PayerCurrency { get; set; }
        /// <summary>
        /// 商户端设备号
        /// </summary>
        [Column("device_id")]
        [StringLength(64)]
        public string DeviceId { get; set; }
    }
}